//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServer.JCDecauxServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCDecauxServiceProxy.IJCDecauxServiceProxy")]
    public interface IJCDecauxServiceProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxServiceProxy/getContractsList", ReplyAction="http://tempuri.org/IJCDecauxServiceProxy/getContractsListResponse")]
        string getContractsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxServiceProxy/getContractsList", ReplyAction="http://tempuri.org/IJCDecauxServiceProxy/getContractsListResponse")]
        System.Threading.Tasks.Task<string> getContractsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxServiceProxy/getStationsList", ReplyAction="http://tempuri.org/IJCDecauxServiceProxy/getStationsListResponse")]
        string getStationsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxServiceProxy/getStationsList", ReplyAction="http://tempuri.org/IJCDecauxServiceProxy/getStationsListResponse")]
        System.Threading.Tasks.Task<string> getStationsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxServiceProxy/getStationsListWithContractName", ReplyAction="http://tempuri.org/IJCDecauxServiceProxy/getStationsListWithContractNameResponse")]
        string getStationsListWithContractName(string contractName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxServiceProxy/getStationsListWithContractName", ReplyAction="http://tempuri.org/IJCDecauxServiceProxy/getStationsListWithContractNameResponse")]
        System.Threading.Tasks.Task<string> getStationsListWithContractNameAsync(string contractName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCDecauxServiceProxyChannel : ApplicationServer.JCDecauxServiceProxy.IJCDecauxServiceProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCDecauxServiceProxyClient : System.ServiceModel.ClientBase<ApplicationServer.JCDecauxServiceProxy.IJCDecauxServiceProxy>, ApplicationServer.JCDecauxServiceProxy.IJCDecauxServiceProxy {
        
        public JCDecauxServiceProxyClient() {
        }
        
        public JCDecauxServiceProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCDecauxServiceProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxServiceProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxServiceProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getContractsList() {
            return base.Channel.getContractsList();
        }
        
        public System.Threading.Tasks.Task<string> getContractsListAsync() {
            return base.Channel.getContractsListAsync();
        }
        
        public string getStationsList() {
            return base.Channel.getStationsList();
        }
        
        public System.Threading.Tasks.Task<string> getStationsListAsync() {
            return base.Channel.getStationsListAsync();
        }
        
        public string getStationsListWithContractName(string contractName) {
            return base.Channel.getStationsListWithContractName(contractName);
        }
        
        public System.Threading.Tasks.Task<string> getStationsListWithContractNameAsync(string contractName) {
            return base.Channel.getStationsListWithContractNameAsync(contractName);
        }
    }
}
